server.port=8440
spring.application.name=contract-services
spring.profiles.active=local

contract-service.datasource.driver=org.postgresql.Driver
contract-service.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
contract-service.datasource.hibernate.jdbc.batch_size=100

company.tax.identifier=5644238012

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=nurtricenter-control-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=10