contract-service.datasource.url=jdbc:postgresql://postgres-contract-services:5432/contract_services
contract-service.datasource.username=contract_services_user
contract-service.datasource.password=KhQPnGzVYFs0BEyh8HwL

kafka.topics.inbound=outbox.event.advice
kafka.topics.outbound=contracts.outbound