server.port=8440
spring.application.name=contract-services
spring.profiles.active=local

contract-service.datasource.driver=org.postgresql.Driver
contract-service.datasource.dialect=org.hibernate.dialect.PostgreSQLDialect
contract-service.datasource.hibernate.jdbc.batch_size=100

company.tax.identifier=5644238012

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=nurtricenter-control-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.max-poll-records=10

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.registry-fetch-interval-seconds=30
eureka.instance.hostname=contract-services
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}